default:
  image: node

stages:
  - build
  - test
  - docker-build
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
build:
  stage: build
  image: node
  tags:
  - gitlab-react
  
  script:
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!"

  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/

test_master_branch:
  stage: test
  image: node
  tags:
  - gitlab-react
  
  script:
    - echo "Testing App"
    - CI=true npm test -- -u
    - echo "Test successfully!"
  
test_feature_branch:
  stage: test
  image: node
  tags:
  - gitlab-react
  only:
    - /^feature-.*$/
  script:
    - echo "Testing App"
    - CI=true npm test
    - echo "Test successfully!"

docker-build:
  stage: docker-build
  image: docker:latest
  tags:
  - gitlab-react
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
 
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST

feature-job:
  tags:
  - gitlab-react
  script:
    - echo "Testing App"
    - CI=true npm test -- -u
    -  npm run build
    - echo "Test successfully!"
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^feature/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^feature/'
      when: manual
      allow_failure: true
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'

deploy-firebase:
  stage: deploy
  tags:
  - gitlab-react
  image: node:latest
  before_script:
    - echo "deploying app to firebase"
  
  script:
    -  npm i -g firebase-tools
    -  npm run build
    - firebase deploy --token "$FIREBASE_TOKEN"
  only:
    refs:
      - master

